### ISSUE TITLE
dist: 0.13.1 on centos - jmx client is not able to connect to server

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-jmx#16]
When installing scylla-server and scylla-jmx from 0.13.1 on centos 7 the jmx client is not able to connect to server

The scylla-jmx is using the correct conf file yet is connecting to 127.0.0.1 that is not present - @amnonh how is the scylla-jmx deciding to which IP it should connect ?

```
Dec 12 21:03:44 server-01.localdomain scylla-jmx[8951]: Using config file: /etc/scylla/scylla.yaml
Dec 12 21:03:44 server-01.localdomain scylla-jmx[8951]: Connecting to http://127.0.0.1:10000
Dec 12 21:03:44 server-01.localdomain scylla-jmx[8951]: Starting the JMX server
Dec 12 21:03:44 server-01.localdomain scylla-jmx[8951]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Dec 12 21:03:44 server-01.localdomain scylla-jmx[8951]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Dec 12 21:03:44 server-01.localdomain scylla-jmx[8951]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: getDroppedMessages()
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: Dec 12, 2015 9:03:45 PM org.apache.cassandra.net.MessagingService log
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: INFO:  getDroppedMessages()
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: Exception in thread "Dropped messages" javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at com.cloudius.urchin.api.APIClient.getRawValue(APIClient.java:150)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at com.cloudius.urchin.api.APIClient.getRawValue(APIClient.java:167)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at com.cloudius.urchin.api.APIClient.getReader(APIClient.java:194)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at com.cloudius.urchin.api.APIClient.getJsonArray(APIClient.java:598)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at com.cloudius.urchin.api.APIClient.getJsonArray(APIClient.java:605)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.apache.cassandra.net.MessagingService.getDroppedMessages(MessagingService.java:190)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.apache.cassandra.net.MessagingService$CheckDroppedMessages.run(MessagingService.java:128)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.util.TimerThread.mainLoop(Timer.java:555)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.util.TimerThread.run(Timer.java:505)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: Caused by: java.net.ConnectException: Connection refused
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.net.PlainSocketImpl.socketConnect(Native Method)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.net.Socket.connect(Socket.java:589)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.http.HttpClient.New(HttpClient.java:308)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.http.HttpClient.New(HttpClient.java:326)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
Dec 12 21:03:45 server-01.localdomain scylla-jmx[8951]: ... 18 more
```

**Comment by slivne** [comment]
@amnonh please provide instructions for a workaround and work on a patch we will need to decide if we are patching 0.13 or providing a workaround solution.

**Comment by amnonh** [comment]
Do you have the jmx command line?
Could it be that the ip address was override from the command line?

**Comment by amnonh** [comment]
The problem is with the commit: bb209e8ce7f9ced3dba8c32fa6953ad2bfa05d75

The scripts/scylla-jmx script always set the ip address and port, it should do that only if the ip address is given.

The simplest workaround would be to remove from the java execution file the part that set the ipaddress:
-Dapiaddress=$API_ADDR -Dapiport=$API_PORT

**Comment by slivne** [comment]
I dont have it install and check
