### ISSUE TITLE
Can not build relocatable package

### ISSUE THREAD

**Issue by datnguyenzzz** [scylladb/scylla-jmx#225]
Issue too many symlinks when building dist.
```
Traceback (most recent call last):
  File "/Users/dat.ngthanh/Documents/My_code/scylladb/tools/jmx/./dist/debian/debian_files_gen.py", line 52, in <module>
    shutil.copytree('dist/debian/debian', 'build/debian/debian')
  File "/usr/lib64/python3.11/shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('dist/debian/debian/scylla-jmx.service', 'build/debian/debian/scylla-jmx.service', "[Errno 40] Too many levels of symbolic links: 'dist/debian/debian/scylla-jmx.service'")]
```

When I tried to list down all symlinks of `dist/debian/debian/scylla-jmx.service `, here is what I got

```
find ./tools/jmx/dist -type l -ls
335518889        0 lrwxr-xr-x    1 dat.ngthanh      staff                  39 Nov 11 10:52 ./tools/jmx/dist/debian/debian/scylla-jmx.service -> ../../common/systemd/scylla-jmx.service
```

**Comment by avikivity** [comment]
What OS are you building on? what filesystem?

**Comment by datnguyenzzz** [comment]
> What OS are you building on? what filesystem?

I'm building on MacOS by using the frozen toolchain - dbuild script. 

Here is my docker info output:

```
Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
  
 Kernel Version: 6.1.55-0-virt
 Operating System: Alpine Linux v3.18
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 1.924GiB
 Name: colima
```
