### ISSUE TITLE
Bad error message when non-existing keyspace is passed to cfhistograms

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-jmx#55]
In the following command, by mistake I queried `keyspace` instead of `keyspace1`. Instead of a graceful error message, I got a scary stack trace:

```
$ nodetool cfhistograms keyspace standard1
error: org.apache.cassandra.metrics:type=Table,keyspace=keyspace,scope=standard1,name=EstimatedPartitionSizeHistogram
-- StackTrace --
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=Table,keyspace=keyspace,scope=standard1,name=EstimatedPartitionSizeHistogram
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at com.scylladb.jmx.utils.APIMBeanServer.getAttribute(APIMBeanServer.java:130)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:273)
	at com.sun.proxy.$Proxy21.getValue(Unknown Source)
	at org.apache.cassandra.tools.NodeProbe.getColumnFamilyMetric(NodeProbe.java:1155)
	at org.apache.cassandra.tools.nodetool.TableHistograms.execute(TableHistograms.java:49)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:265)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:175)
```

**Comment by tzach** [comment]
@amnonh can you please take a look?

**Comment by amnonh** [comment]
I've check, and this is how the nodetool/cassandra works.

I run a cassandra docker container and did the same:
```
# nodetool cfhistograms keyspace standard1
error: org.apache.cassandra.metrics:type=Table,keyspace=keyspace,scope=standard1,name=EstimatedPartitionSizeHistogram
-- StackTrace --
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=Table,keyspace=keyspace,scope=standard1,name=EstimatedPartitionSizeHistogram
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:273)
	at com.sun.proxy.$Proxy20.getValue(Unknown Source)
	at org.apache.cassandra.tools.NodeProbe.getColumnFamilyMetric(NodeProbe.java:1203)
	at org.apache.cassandra.tools.nodetool.TableHistograms.execute(TableHistograms.java:49)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:248)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:162)
```

It's not a problem with the jmx but with the nodetool's nodeprobe implementation, I suggest to close the issue

**Comment by slivne** [comment]
So lets fix this in nodetool if nodetool is the problem. If C* has the issue as well - you can create a C* issues as well and send a patch for that as well.

**Comment by amnonh** [comment]
See also
https://issues.apache.org/jira/browse/CASSANDRA-14410

**Comment by bhalevy** [comment]
Saw this in [dtest-release/128/testReport/nodetool_additional_test/TestNodetool/cfhistograms_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/128/testReport/nodetool_additional_test/TestNodetool/cfhistograms_test/):
```
Error Message
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/resources/cassandra/bin/nodetool -h localhost -p 7115 cfhistograms keyspace1 standard1' failed; exit status: 2; stderr: error: org.apache.cassandra.metrics:type=Table,keyspace=keyspace1,scope=standard1,name=EstimatedPartitionSizeHistogram
-- StackTrace --
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=Table,keyspace=keyspace1,scope=standard1,name=EstimatedPartitionSizeHistogram
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at com.scylladb.jmx.utils.APIMBeanServer.getAttribute(APIMBeanServer.java:140)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:273)
	at com.sun.proxy.$Proxy21.getValue(Unknown Source)
	at org.apache.cassandra.tools.NodeProbe.getColumnFamilyMetric(NodeProbe.java:1352)
	at org.apache.cassandra.tools.nodetool.TableHistograms.execute(TableHistograms.java:62)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:261)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:171)


-------------------- >> begin captured logging << --------------------
dtest: DEBUG: nodetool_additional_test.TestNodetool.cfhistograms_testcfhistograms_test - cluster ccm directory: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-KRiHDR
dtest: DEBUG: nodetool_additional_test.TestNodetool.cfhistograms_testcfhistograms_test - Allocated cluster ID 15: /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-KRiHDR
--------------------- >> end captured logging << ---------------------
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 804, in cfhistograms_test
    res = self._get_cfhistogram(node, "keyspace1", "standard1")
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 773, in _get_cfhistogram
    out = node.nodetool("cfhistograms " + ks + " " + cf, True)[0]
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 718, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
```

**Comment by bhalevy** [comment]
It looks like this worked [dtest-release/176/testReport/nodetool_additional_test/TestNodetool/cfhistograms_test/](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/176/testReport/nodetool_additional_test/TestNodetool/cfhistograms_test/):
```
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/resources/cassandra/bin/nodetool -h localhost -p 7109 cfhistograms keyspace1 standard1' failed; exit status: 1; stdout: nodetool: Unknown table: standard1 or keyspace: keyspace1
```

The test still fails but the bad error message is gone so I think this issue can be closed.
